# -*- coding: utf-8 -*-
"""Seaborn_class2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnTT5yfzCQg8cwRjvk3oCxllQlym9kzb

# Seaborn – Class 2: Categorical Plots

## What Are Categorical Plots?

Categorical plots visualize data where at least one variable is **categorical**  
(e.g., day of week, gender, class).

Seaborn gives several easy options to:
- Compare **counts** or **averages** across categories
- Understand spread & distribution

## barplot() vs countplot()
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

tips = sns.load_dataset('tips')
tips.head()

sns.barplot(x = tips['day'],y = tips['total_bill'])
# this shows avg valueof total bill on days of weeks.
#balck vertical line shows the variance , more longer the line , more the variaence.

sns.countplot(x = tips['day'])

tips['day'].value_counts()

"""## boxplot() & violinplot()"""

# creating a box-plot:
sns.boxplot(x = tips['day'],y= tips['total_bill'])
#points shows numbers of outliers.

# violin plot
sns.violinplot(x = tips['day'],y=tips['total_bill'])
# it reoresents boxplot and also shows a distribution.
# streched tall shows more number of outliers.

"""## stripplot() & swarmplot()"""

sns.stripplot(x=tips['day'],y=tips['total_bill'])

sns.swarmplot(x=tips['day'],y=tips['total_bill'])

# swarm and violin together:
sns.swarmplot(x=tips['day'],y=tips['total_bill'])
sns.violinplot(x = tips['day'],y=tips['total_bill'])

"""| Plot        | Best for |
|-------------|-----------|
| **barplot** | Compare average values across categories |
| **countplot** | Show how many items fall in each category |
| **boxplot** | See median, quartiles, and outliers |
| **violinplot** | Same as boxplot + shows distribution |
| **stripplot** | View every observation (good for small data) |
| **swarmplot** | Like stripplot but avoids overlap |

"""

